# Generated by Django 2.2.9 on 2020-05-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
