# Generated by Django 2.2.9 on 2020-05-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(default=1, verbose_name='Portada del libro'),
            preserve_default=False,
        ),
    ]
